/*
 * This file is generated by jOOQ.
 */
package jooq_generated;


import jooq_generated.tables.User;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;
}
